// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RedGenealogica.Web.Data;

#nullable disable

namespace RedGenealogica.Web.Migrations
{
    [DbContext(typeof(ContextoAplicacion))]
    [Migration("20260329063459_SepararEstadoReferido")]
    partial class SepararEstadoReferido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.MovimientoPuntos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPuntos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferidoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosPuntos", (string)null);
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsSimulado")
                        .HasColumnType("boolean");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreCuentaEnmascarado")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PlataformaPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.RangoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IconoCss")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosMaximos")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosMinimos")
                        .HasColumnType("integer");

                    b.Property<int>("TipoRango")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RangosUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ColorPrincipal = "#8B5A2B",
                            IconoCss = "bi-shield",
                            NombreVisible = "Cobre",
                            Orden = 1,
                            PuntosMaximos = 99,
                            PuntosMinimos = 0,
                            TipoRango = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ColorPrincipal = "#B08D57",
                            IconoCss = "bi-shield-check",
                            NombreVisible = "Bronce",
                            Orden = 2,
                            PuntosMaximos = 299,
                            PuntosMinimos = 100,
                            TipoRango = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            ColorPrincipal = "#BFC1C2",
                            IconoCss = "bi-award",
                            NombreVisible = "Plata",
                            Orden = 3,
                            PuntosMaximos = 599,
                            PuntosMinimos = 300,
                            TipoRango = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            ColorPrincipal = "#D4AF37",
                            IconoCss = "bi-trophy",
                            NombreVisible = "Oro",
                            Orden = 4,
                            PuntosMaximos = 999,
                            PuntosMinimos = 600,
                            TipoRango = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            ColorPrincipal = "#62D0FF",
                            IconoCss = "bi-gem",
                            NombreVisible = "Platino",
                            Orden = 5,
                            PuntosMaximos = 1499,
                            PuntosMinimos = 1000,
                            TipoRango = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            ColorPrincipal = "#00E5FF",
                            IconoCss = "bi-gem",
                            NombreVisible = "Diamante",
                            Orden = 6,
                            PuntosMaximos = 2147483647,
                            PuntosMinimos = 1500,
                            TipoRango = 6
                        });
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Referido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("PagoConfirmado")
                        .HasColumnType("boolean");

                    b.Property<int?>("PagoReferidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("PagoUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("UsuarioConvertidoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PagoReferidoId");

                    b.HasIndex("PagoUsuarioId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioConvertidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Referidos", (string)null);
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.RegistroWebhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegistrosWebhook");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoReferido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("IdUsuarioPadre")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("TipoRangoActual")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferido")
                        .IsUnique();

                    b.HasIndex("DocumentoIdentidad");

                    b.HasIndex("IdUsuarioPadre");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedGenealogica.Web.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.MovimientoPuntos", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Referido", "Referido")
                        .WithMany()
                        .HasForeignKey("ReferidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RedGenealogica.Web.Models.Usuario", "Usuario")
                        .WithMany("MovimientosPuntos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Pago", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Producto", "Producto")
                        .WithMany("Pagos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedGenealogica.Web.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Referido", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Pago", "PagoReferido")
                        .WithMany()
                        .HasForeignKey("PagoReferidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RedGenealogica.Web.Models.Pago", "PagoUsuario")
                        .WithMany()
                        .HasForeignKey("PagoUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RedGenealogica.Web.Models.Producto", "Producto")
                        .WithMany("Referidos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RedGenealogica.Web.Models.Usuario", "UsuarioConvertido")
                        .WithMany()
                        .HasForeignKey("UsuarioConvertidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RedGenealogica.Web.Models.Usuario", "Usuario")
                        .WithMany("ReferidosRegistrados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PagoReferido");

                    b.Navigation("PagoUsuario");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioConvertido");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Usuario", b =>
                {
                    b.HasOne("RedGenealogica.Web.Models.Usuario", "UsuarioPadre")
                        .WithMany("ReferidosDirectos")
                        .HasForeignKey("IdUsuarioPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioPadre");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Producto", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Referidos");
                });

            modelBuilder.Entity("RedGenealogica.Web.Models.Usuario", b =>
                {
                    b.Navigation("MovimientosPuntos");

                    b.Navigation("Pagos");

                    b.Navigation("ReferidosDirectos");

                    b.Navigation("ReferidosRegistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
