CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(120) NOT NULL,
        "Descripcion" character varying(500),
        "Precio" numeric(18,2) NOT NULL,
        "ComisionNivel1Porcentaje" numeric(5,2) NOT NULL,
        "ComisionNivel2Porcentaje" numeric(5,2) NOT NULL,
        "ComisionNivel3Porcentaje" numeric(5,2) NOT NULL,
        "StockDisponible" integer,
        "ImagenUrl" character varying(250),
        "Activo" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Productos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "RangosUsuario" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TipoRango" integer NOT NULL,
        "PuntosMinimos" integer NOT NULL,
        "PuntosMaximos" integer NOT NULL,
        "Orden" integer NOT NULL,
        "NombreVisible" character varying(50) NOT NULL,
        "BonusComisionPorcentaje" numeric(5,2) NOT NULL,
        "ColorPrincipal" character varying(30),
        "IconoCss" character varying(80),
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_RangosUsuario" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "RegistrosWebhook" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IdPago" text NOT NULL,
        "Estado" text NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RegistrosWebhook" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombres" character varying(100) NOT NULL,
        "Apellidos" character varying(100) NOT NULL,
        "CodigoReferido" character varying(30) NOT NULL,
        "DocumentoIdentidad" character varying(50),
        "FotoPerfilUrl" character varying(250),
        "PuntosAcumulados" integer NOT NULL,
        "TipoRangoActual" integer NOT NULL,
        "EstadoUsuario" integer NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        "FechaActivacion" timestamp with time zone,
        "SaldoDisponible" numeric(18,2) NOT NULL,
        "SaldoPendienteRetiro" numeric(18,2) NOT NULL,
        "CbuAlias" character varying(100),
        "IdUsuarioPadre" integer,
        "CiclosCompletados" integer NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Usuarios_IdUsuarioPadre" FOREIGN KEY ("IdUsuarioPadre") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "Notificaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Tipo" integer NOT NULL,
        "Titulo" character varying(120) NOT NULL,
        "Mensaje" character varying(300) NOT NULL,
        "UrlAccion" character varying(200),
        "Leida" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notificaciones_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "Pagos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ProductoId" integer NOT NULL,
        "Monto" numeric(18,2) NOT NULL,
        "EstadoPago" integer NOT NULL,
        "PlataformaPago" character varying(100) NOT NULL,
        "ReferenciaExterna" character varying(150),
        "NombreCuentaEnmascarado" character varying(150),
        "EsSimulado" boolean NOT NULL,
        "FechaSolicitud" timestamp with time zone NOT NULL,
        "FechaConfirmacion" timestamp with time zone,
        "Confirmado" boolean NOT NULL,
        CONSTRAINT "PK_Pagos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pagos_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Pagos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "SolicitudesRetiro" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Monto" numeric(18,2) NOT NULL,
        "Estado" integer NOT NULL,
        "CbuAlias" character varying(100) NOT NULL,
        "ReferenciaTransferencia" character varying(150),
        "NotaAdmin" character varying(300),
        "FechaSolicitud" timestamp with time zone NOT NULL,
        "FechaResolucion" timestamp with time zone,
        "AdminResolvidoId" integer,
        CONSTRAINT "PK_SolicitudesRetiro" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SolicitudesRetiro_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "Referidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "ProductoId" integer NOT NULL,
        "NombreCompleto" character varying(150) NOT NULL,
        "CorreoElectronico" character varying(150),
        "Telefono" character varying(30),
        "PagoUsuarioId" integer,
        "PagoReferidoId" integer,
        "Estado" integer NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        "FechaActivacion" timestamp with time zone,
        "UsuarioConvertidoId" integer,
        "PagoConfirmado" boolean NOT NULL,
        CONSTRAINT "PK_Referidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Referidos_Pagos_PagoReferidoId" FOREIGN KEY ("PagoReferidoId") REFERENCES "Pagos" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Referidos_Pagos_PagoUsuarioId" FOREIGN KEY ("PagoUsuarioId") REFERENCES "Pagos" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Referidos_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Referidos_Usuarios_UsuarioConvertidoId" FOREIGN KEY ("UsuarioConvertidoId") REFERENCES "Usuarios" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Referidos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE TABLE "MovimientosPuntos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "CantidadPuntos" integer NOT NULL,
        "Motivo" character varying(150) NOT NULL,
        "ReferidoId" integer,
        "FechaMovimiento" timestamp with time zone NOT NULL,
        "Monto" numeric(18,2) NOT NULL,
        "Nivel" integer NOT NULL,
        CONSTRAINT "PK_MovimientosPuntos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovimientosPuntos_Referidos_ReferidoId" FOREIGN KEY ("ReferidoId") REFERENCES "Referidos" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_MovimientosPuntos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (1, TRUE, 0.0, '#8B5A2B', 'bi-shield', 'Cobre', 1, 99, 0, 1);
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (2, TRUE, 10.0, '#B08D57', 'bi-shield-check', 'Bronce', 2, 299, 100, 2);
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (3, TRUE, 20.0, '#BFC1C2', 'bi-award', 'Plata', 3, 599, 300, 3);
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (4, TRUE, 40.0, '#D4AF37', 'bi-trophy', 'Oro', 4, 999, 600, 4);
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (5, TRUE, 60.0, '#62D0FF', 'bi-gem', 'Platino', 5, 1499, 1000, 5);
    INSERT INTO "RangosUsuario" ("Id", "Activo", "BonusComisionPorcentaje", "ColorPrincipal", "IconoCss", "NombreVisible", "Orden", "PuntosMaximos", "PuntosMinimos", "TipoRango")
    VALUES (6, TRUE, 80.0, '#00E5FF', 'bi-gem', 'Diamante', 6, 2147483647, 1500, 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_MovimientosPuntos_ReferidoId" ON "MovimientosPuntos" ("ReferidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_MovimientosPuntos_UsuarioId" ON "MovimientosPuntos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Notificaciones_UsuarioId_Leida" ON "Notificaciones" ("UsuarioId", "Leida");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Pagos_ProductoId" ON "Pagos" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Pagos_UsuarioId" ON "Pagos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Referidos_PagoReferidoId" ON "Referidos" ("PagoReferidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Referidos_PagoUsuarioId" ON "Referidos" ("PagoUsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Referidos_ProductoId" ON "Referidos" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Referidos_UsuarioConvertidoId" ON "Referidos" ("UsuarioConvertidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Referidos_UsuarioId" ON "Referidos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_SolicitudesRetiro_UsuarioId" ON "SolicitudesRetiro" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "EmailIndex" ON "Usuarios" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_CodigoReferido" ON "Usuarios" ("CodigoReferido");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE INDEX "IX_Usuarios_IdUsuarioPadre" ON "Usuarios" ("IdUsuarioPadre");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Usuarios" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    PERFORM setval(
        pg_get_serial_sequence('"RangosUsuario"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "RangosUsuario") + 1,
            nextval(pg_get_serial_sequence('"RangosUsuario"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260405161904_InicialLimpia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260405161904_InicialLimpia', '9.0.1');
    END IF;
END $EF$;
COMMIT;

